"""tenant table create

Revision ID: 5a00ff82a9f4
Revises: d6ba8c13303e
Create Date: 2023-02-15 05:08:52.532126

"""
from alembic import op
import sqlalchemy as sa


from app.alembic.tenant import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = '5a00ff82a9f4'
down_revision = 'd6ba8c13303e'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    # schema_quoted = preparer.format_schema(schema)
    tenants = """
    CREATE TABLE IF NOT EXISTS shared.tenants (
       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       uuid uuid UNIQUE,
       name varchar(100),
       schema varchar(100),
       host varchar(100)
      );
    """
    op.execute(tenants)

    pass


def downgrade() -> None:
    # preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    # schema_quoted = preparer.format_schema(schema)
    op.execute("DROP TABLE IF EXISTS shared.tenants CASCADE;")

    pass
