"""shared tables create

Revision ID: 623b3ab58a36
Revises: a155fef34a39
Create Date: 2023-02-25 15:58:35.491363

"""
from alembic import op
import sqlalchemy as sa


from app.alembic.tenant import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = '623b3ab58a36'
down_revision = 'fe69bd1396dc'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('schema', sa.String(length=256), nullable=False),
                    sa.Column('host', sa.String(length=256), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
                    sa.UniqueConstraint('host', name=op.f('uq_tenants_host')),
                    sa.UniqueConstraint('schema', name=op.f('uq_tenants_schema')),
                    schema='shared'
                    )
    op.create_index(op.f('ix_shared_tenants_name'), 'tenants', ['name'], unique=True, schema='shared')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_tenants_name'), table_name='tenants', schema='shared')
    op.drop_table('tenants', schema='shared')
    # ### end Alembic commands ###
