"""table created

Revision ID: fe69bd1396dc
Revises: 
Create Date: 2023-02-03 11:44:59.756732

"""
from alembic import op
import sqlalchemy as sa


from app.alembic.tenant import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = 'fe69bd1396dc'
down_revision = None
branch_labels = None
depends_on = None

@for_each_tenant_schema
def upgrade() -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('schema', sa.String(length=256), nullable=False),
    sa.Column('host', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('host', name=op.f('uq_tenants_host')),
    sa.UniqueConstraint('schema', name=op.f('uq_tenants_schema')),
    schema='shared'
    )
    op.create_index(op.f('ix_shared_tenants_name'), 'tenants', ['name'], unique=True, schema='shared')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='tenant_default'
    )
    op.create_index(op.f('ix_tenant_default_users_email'), 'users', ['email'], unique=True, schema='tenant_default')
    op.create_index(op.f('ix_tenant_default_users_full_name'), 'users', ['full_name'], unique=False, schema='tenant_default')
    op.create_index(op.f('ix_tenant_default_users_id'), 'users', ['id'], unique=False, schema='tenant_default')
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade() -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_default_users_id'), table_name='users', schema='tenant_default')
    op.drop_index(op.f('ix_tenant_default_users_full_name'), table_name='users', schema='tenant_default')
    op.drop_index(op.f('ix_tenant_default_users_email'), table_name='users', schema='tenant_default')
    op.drop_table('users', schema='tenant_default')
    op.drop_index(op.f('ix_shared_tenants_name'), table_name='tenants', schema='shared')
    op.drop_table('tenants', schema='shared')
    # ### end Alembic commands ###
