"""table created

Revision ID: fe69bd1396dc
Revises: 
Create Date: 2023-02-03 11:44:59.756732

"""
from alembic import op
import sqlalchemy as sa


from app.alembic.tenant import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = 'fe69bd1396dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
